# Generated by Django 3.1.2 on 2020-11-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='year_in_school',
        ),
    ]
